---
abstract: "a mashup for consuming multiple date formats\r"
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Modern::Perl: 0
  Moose: 0
  MooseX::ClassCompositor: 0
  Test::MockTime: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  YAML::Any: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Mashup-Shiras
requires:
  DateTime: 0
  DateTime::Format::DateManip: 0
  DateTime::Format::Epoch: 0.013
  DateTime::Format::Excel: 0
  Moose::Role: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Smart::Comments: 0
  version: 0.94
version: v0.007_003
