---
abstract: 'A Moose role with four date attributes'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Data::Dumper: 0
  Moose: 0
  MooseX::HasDefaults::RO: 0
  MooseX::ShortCut::BuildInstance: 0
  Test::MockTime: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  YAML::Any: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Mashup-Shiras
provides:
  DateTimeX::Mashup::Shiras:
    file: lib/DateTimeX/Mashup/Shiras.pm
    version: v0.30.2
  DateTimeX::Mashup::Shiras::Types:
    file: lib/DateTimeX/Mashup/Shiras/Types.pm
    version: v0.30.2
requires:
  DateTime: 0
  DateTime::Format::Epoch: 0.013
  DateTime::Format::Flexible: 0
  DateTimeX::Format::Excel: v0.12.0
  Moose::Role: 0
  Smart::Comments: 0
  Type::Library: 0
  Type::Utils: 0.046
  Types::Standard: 0
  lib: 0
  perl: 5.010
  strict: 0
  version: 0.94
  warnings: 0
resources:
  bugtracker: https://github.com/jandrew/DateTimeX-Mashup-Shiras/issues
  homepage: https://github.com/jandrew/DateTimeX-Mashup-Shiras
  repository: https://github.com/jandrew/DateTimeX-Mashup-Shiras.git
version: v0.30.2
x_authority: cpan:JANDREW
