---
abstract: 'A Moose role with date attributes'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: 0
  DateTime: 0
  DateTime::Format::Epoch: 0.013
  DateTime::Format::Flexible: 0
  DateTimeX::Format::Excel: 0.012
  List::Util: 1.33
  Moose: 2.1213
  Moose::Role: 0
  MooseX::Role::Parameterized: 0
  MooseX::ShortCut::BuildInstance: 1.028
  Test::MockTime: 0
  Test::Moose: 0
  Test::Most: 0
  Type::Tiny: 1.000
  YAML::Any: 0
  perl: 5.010
  version: 0.77
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Mashup-Shiras
provides:
  DateTimeX::Mashup::Shiras:
    file: lib/DateTimeX/Mashup/Shiras.pm
    version: v0.32.6
  DateTimeX::Mashup::Shiras::Types:
    file: lib/DateTimeX/Mashup/Shiras/Types.pm
    version: v0.32.6
requires:
  DateTime: 0
  DateTime::Format::Epoch: 0.013
  DateTime::Format::Flexible: 0
  DateTimeX::Format::Excel: 0.012
  Moose::Role: 0
  MooseX::Role::Parameterized: 0
  Smart::Comments: 0
  Type::Library: 0
  Type::Utils: 1.000
  Types::Standard: 0
  lib: 0
  perl: 5.010
  strict: 0
  version: 0.77
  warnings: 0
resources:
  bugtracker: https://github.com/jandrew/DateTimeX-Mashup-Shiras/issues
  homepage: https://github.com/jandrew/DateTimeX-Mashup-Shiras
  repository: https://github.com/jandrew/DateTimeX-Mashup-Shiras.git
version: v0.32.6
x_authority: cpan:JANDREW
x_contributors:
  - 'Toby Inkster <tobyink@cpan.org>'
